---
- hosts: all
  become: yes
  tasks:
    - name: "Criação do Usuario suporte"
      ansible.builtin.user:
        name: suporte
        comment: suporte
        uid: 5000
        group: root